apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ujwutw02z-python 
  janus-idp.io/tekton: ujwutw02z-python
  backstage.io/kubernetes-id: ujwutw02z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ujwutw02z-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml