apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ujwutw02z-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ujwutw02z-python 
  name: ujwutw02z-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ujwutw02z-python 
